// Pixel art : chaque sprite est une grille de caractères -> couleurs de PAL.
// '.' = transparent. Validé par les tests (largeur constante, couleurs connues).
export const PAL = {
  D: '#3b2416', B: '#8a5a34', C: '#ecd7ae', K: '#20160f',
  W: '#ffffff', G: '#7d93a6', g: '#c6d3dd', q: '#6f4623',
  O: '#f2913d', R: '#e5484d', P: '#f0a1a1',
  U: '#4a6fae', Y: '#f2c14e'
};

export const SPRITES = {
  egg: [
    '................',
    '......DDDD......',
    '....DDggggDD....',
    '...DggggggggD...',
    '..DggGGGgggggD..',
    '.DgggGGGGGggggD.',
    '.DggggGGGgggggD.',
    'DggggggggggggggD',
    'DgggGGggggGGgggD',
    'DggggggggggggggD',
    '.DggggggggggggD.',
    '.DggggggggggggD.',
    '..DggggggggggD..',
    '...DDggggggDD...',
    '.....DDDDDD.....',
    '................'
  ],
  baby: [
    '....DD....DD....',
    '...DqDBBBBDqD...',
    '..DBBBBBBBBBBD..',
    '..DBWKBBBBWKBD..',
    '..DBKKBBBBKKBD..',
    '..DPBBCCCCBBPD..',
    '..DBCCCKKCCCBD..',
    '..DBBCCCCCCBBD..',
    '.DBBCCCCCCCCBBD.',
    '.DBqCCCCCCCCqBD.',
    '.DBqCCCCCCCCqBD.',
    '..DBCCCCCCCCBD..',
    '..DBBBBBBBBBDqD.',
    '...DBBD..DBBD...',
    '....DD....DD....',
    '................'
  ],
  child: [
    '....DD....DD....',
    '...DqDBBBBDqD...',
    '..DBBBBBBBBBBD..',
    '..DBWKBBBBWKBD..',
    '..DBKKBBBBKKBD..',
    '..DPBBCCCCBBPD..',
    '..DBCCCKKCCCBD..',
    '..DBBCCCCCCBBD..',
    '..DBBBBBBBBBBD..',
    '.DBqCCCCCCCqBD..',
    '.DBqCCCCCCCqBD..',
    '.DBqCCCCCCCqBDqD',
    '..DBCCCCCCBBDqqD',
    '..DBBBBBBBBDqqD.',
    '..DBBD..DBBD.DD.',
    '...DD....DD.....'
  ],
  adult: [
    '...DD......DD...',
    '...DqDBBBBDqD...',
    '...DBBBBBBBBD...',
    '..DBWKBBBBWKBD..',
    '..DBKKBBBBKKBD..',
    '..DPBBCCCCBBPD..',
    '..DBCCCKKCCCBD..',
    '..DBBCCCCCCBBD..',
    '..DBBBBBBBBBBD..',
    '.DBBCCCCCCCBBD..',
    '.DBqCCCCCCCqBD..',
    '.DBqCCCCCCCqBD..',
    '.DBqCCCCCCCqBDqD',
    '.DBqCCCCCCCqBDqD',
    '..DBCCCCCCBBDqqD',
    '..DBBBBBBBBDqqqD',
    '..DBBD..DBBDDqqD',
    '...DD....DD..DD.'
  ],
  poop: [
    '....q...',
    '..qqqq..',
    '.qqqqqq.',
    'qqqqqqqq'
  ],
  fish: [
    '...OO.....',
    '.OOOOOO..O',
    'OWKOOOOOOO',
    '.OOOOOO..O',
    '...OO.....'
  ],
  heart: [
    '.RR..RR.',
    'RRRRRRRR',
    'RRRRRRRR',
    '.RRRRRR.',
    '..RRRR..',
    '...RR...'
  ],
  heron: [
    '.....gg.....',
    '....gggK....',
    'OOOOgggg....',
    '.....ggg....',
    '.....gg.....',
    '.....gg.....',
    '....gggg....',
    '...GGgggg...',
    '..GGGggggg..',
    '..GGGGgggg..',
    '...GGGGgg...',
    '.....DD.....',
    '.....D.D....',
    '....DD.DD...'
  ],

  // Pas de marche : les pattes alternent (2e image du cycle)
  babyWalk: [
    '....DD....DD....',
    '...DqDBBBBDqD...',
    '..DBBBBBBBBBBD..',
    '..DBWKBBBBWKBD..',
    '..DBKKBBBBKKBD..',
    '..DPBBCCCCBBPD..',
    '..DBCCCKKCCCBD..',
    '..DBBCCCCCCBBD..',
    '.DBBCCCCCCCCBBD.',
    '.DBqCCCCCCCCqBD.',
    '.DBqCCCCCCCCqBD.',
    '..DBCCCCCCCCBD..',
    '..DBBBBBBBBBDqD.',
    '..DBBD....DBBD..',
    '...DD......DD...',
    '................'
  ],
  childWalk: [
    '....DD....DD....',
    '...DqDBBBBDqD...',
    '..DBBBBBBBBBBD..',
    '..DBWKBBBBWKBD..',
    '..DBKKBBBBKKBD..',
    '..DPBBCCCCBBPD..',
    '..DBCCCKKCCCBD..',
    '..DBBCCCCCCBBD..',
    '..DBBBBBBBBBBD..',
    '.DBqCCCCCCCqBD..',
    '.DBqCCCCCCCqBD..',
    '.DBqCCCCCCCqBDqD',
    '..DBCCCCCCBBDqqD',
    '..DBBBBBBBBDqqD.',
    '.DBBD....DBBDDD.',
    '..DD......DD....'
  ],
  adultWalk: [
    '...DD......DD...',
    '...DqDBBBBDqD...',
    '...DBBBBBBBBD...',
    '..DBWKBBBBWKBD..',
    '..DBKKBBBBKKBD..',
    '..DPBBCCCCBBPD..',
    '..DBCCCKKCCCBD..',
    '..DBBCCCCCCBBD..',
    '..DBBBBBBBBBBD..',
    '.DBBCCCCCCCBBD..',
    '.DBqCCCCCCCqBD..',
    '.DBqCCCCCCCqBD..',
    '.DBqCCCCCCCqBDqD',
    '.DBqCCCCCCCqBDqD',
    '..DBCCCCCCBBDqqD',
    '..DBBBBBBBBDqqqD',
    '.DBBD....DBBDqqD',
    '..DD......DD.DD.'
  ],

  // LE CHASSEUR : silhouette d'homme, chapeau à large bord et fusil en travers.
  // Dessiné plutôt qu'emoji : à l'échelle des tuiles il doit se reconnaître de
  // loin et faire peur, ce qu'aucun emoji ne rend.
  chasseur: [
    '......KKKK......',
    '.....KKKKKK.....',
    '...KKKKKKKKKK...',
    '.....CCCCCC.....',
    '.....CKCCKC.....',
    '.....CCCCCC.....',
    '....DDDDDDDD....',
    '...DDDDDDDDDD...',
    '...DDDDDDDDDDqq.',
    '...DDDDDDDDDDq..',
    '...DDDDDDDDDD...',
    '....DDDDDDDD....',
    '....DD....DD....',
    '....DD....DD....',
    '....KK....KK....'
  ]
};
